QUESTION_DATA = [
    {"text": "Pointers were not used in the original C programming language; they were added later on in C++.", "answer": "False"},
    {"text": "RAM stands for Random Access Memory.", "answer": "True"},
    {"text": "Ada Lovelace is often considered the first computer programmer.", "answer": "True"},
    {"text": "'HTML' stands for Hypertext Markup Language.", "answer": "True"},
    {"text": "In most programming languages, the operator ++ is equivalent to the statement '+= 1'.", "answer": "True"},
    {"text": "Time on Computers is measured via the EPOX System.", "answer": "False"},
    {"text": "The Windows 7 operating system has six main editions.", "answer": "True"},
    {"text": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.", "answer": "False"},
    {"text": "Linux was first created as an alternative to Windows XP.", "answer": "False"},
    {"text": "The Python programming language gets its name from the British comedy group 'Monty Python.'", "answer": "True"},
    {"text": "The common software-programming acronym 'I18N' comes from the term 'Interlocalization'.", "answer": "False"},
    {"text": "The very first recorded computer 'bug' was a moth found inside a Harvard Mark II computer.", "answer": "True"},
    {"text": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.", "answer": "False"},
    {"text": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ", "answer": "True"},
    {"text": "AMD created the first consumer 64-bit processor.", "answer": "True"},
    {"text": "Early RAM was directly seated onto the motherboard and could not be easily removed.", "answer": "True"},
    {"text": "The first dual-core CPU was the Intel Pentium D.", "answer": "False"},
    {"text": "Android versions are named in alphabetical order.", "answer": "True"},
    {"text": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.", "answer": "False"},
    {"text": "A Boolean value of '0' represents which of these words?", "answer": "False"},
]